"""
changelog_writer.py — CHANGELOG.md regeneration engine.

Regenerates CHANGELOG.md in full from two sources of truth:
  - Per-release notes files under release-notes/vX.Y.Z.md
  - The bug ledger under bugs_dir/

Each CHANGELOG entry has exactly three content sections:
  ### Implemented   — features from the release notes
  ### Fixed         — resolved bugs from the release notes, classified correctly
  ### Known Issues  — projected from the bug ledger against PUBLISHED versions

Disclosure policy: a bug is disclosed in Known Issues ONLY if it affected a
PUBLISHED version (a version a user could actually have run). Bugs born and
fixed entirely between public tags are never published; they remain in the
internal ledger.

Public IDs use the format KI-<earliest-affected-PUBLISHED-version-no-v>.<counter>
(e.g. KI-1.0.0.1). Once assigned they are read from the bug file and never
recomputed at regeneration.

Public-ID assignment is gated on ## Affects parsing as a recognisable version
string (e.g. 'v1.2.3', '1.2.3').  Prose values such as
'(internal — plugin era; no KI)' are not version strings; they produce a
warning to stderr naming the offending file and no Public ID is assigned.
Internal bugs should omit the ## Affects section entirely rather than using
a prose placeholder.

Internal BUG-NNNN identifiers never appear in generated CHANGELOG output.

Entry point:
    regenerate(repo_root, released_versions, published_manifest, bugs_dir) -> str

Cleanup entry point:
    remove_bogus_public_ids(bugs_dir, published_manifest) -> list[pathlib.Path]
    Removes Public IDs from bug files whose ## Affects does not parse as a
    version string.  Idempotent: running twice produces the same output as
    running once.  Returns the list of files modified.

Manifest loader:
    load_published_manifest(repo_root) -> list[str]
    Returns [] when release-notes/PUBLISHED is absent (empty-manifest semantics:
    no published releases, every bug entry is internal — the correct reading for
    managed dev trees that predate the v1.17 disclosure architecture).
    Returns [] when the file exists but is empty (same: pre-publication state).
"""

from __future__ import annotations

import pathlib
import re
import sys
from collections import defaultdict
from typing import NamedTuple

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_HEADER = (
    "# Changelog\n\n"
    "<!-- Auto-generated by changelog_writer.py. Do not edit manually. -->\n"
    "<!-- Known Issues covers defects that existed in PUBLISHED releases only. -->\n"
    "<!-- Internal-only defects are tracked in the bug ledger but not disclosed. -->\n"
)

# Pattern that matches internal bug identifiers — must never appear in output.
_BUG_ID_PATTERN = re.compile(r"BUG-[0-9]")

# Sections in release notes that contain implemented (feature) content.
_IMPLEMENTED_HEADINGS = frozenset(
    {"features", "what shipped", "implemented"}
)

# Sections in release notes that contain fixed (bug) content.
_FIXED_HEADINGS = frozenset(
    {"bug fixes", "bugs resolved", "fixed"}
)

# Sections in release notes that contain the release summary.
_SUMMARY_HEADINGS = frozenset({"summary"})

# Section headings to skip when extracting content (we compute these ourselves).
_SKIP_HEADINGS = frozenset({
    "known issues",
    "bugs skipped",
    "deprecations",
    "breaking changes",
    "upgrade notes",
    "documentation",
    "other changes",
    "status",
    "release date",
    "released by",
})


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


class BugRecord(NamedTuple):
    """Parsed representation of a single bug file."""
    bug_id: str          # e.g. "BUG-0023"
    slug: str            # e.g. "BUG-0023-tmux-split-flag"
    symptom: str         # first non-empty line of ## Symptom section
    status: str          # open / resolved / wontdo / etc.
    affects: str         # version string e.g. "v1.0.0", or "" if absent
    fixed_in: str        # version string e.g. "v1.16.2", or "" if unset
    public_id: str       # e.g. "KI-1.0.0.1", or "" if not yet assigned
    wontdo_reason: str   # reason from ## Status if wontdo, else ""
    file_path: pathlib.Path


class ReleaseEntry(NamedTuple):
    """Parsed content from a single release-notes/vX.Y.Z.md file."""
    version: str             # e.g. "v1.16.2"
    date: str                # e.g. "2026-07-11"
    summary: str             # one-line summary (first sentence of ## Summary)
    implemented_lines: list  # lines from Features / What Shipped sections
    fixed_bug_ids: list      # BUG-NNNN ids resolved in this release
    fixed_other_lines: list  # non-BUG-NNNN fixed items (non-tracked bugs)


# ---------------------------------------------------------------------------
# Semver comparison helper
# ---------------------------------------------------------------------------


def _parse_version(v: str) -> tuple:
    """Parse a version string like 'v1.2.3' into a comparable tuple.

    Returns (major, minor, patch) as integers. Strips leading 'v' or 'ai_v'.
    Non-numeric trailing components are stripped.
    """
    clean = v.lstrip("v")
    if clean.startswith("ai_"):
        clean = clean[3:]
    parts = clean.split(".")
    result = []
    for p in parts[:3]:
        try:
            result.append(int(p))
        except ValueError:
            break
    # Pad to 3 components
    while len(result) < 3:
        result.append(0)
    return tuple(result)


def _version_gte(v1: str, v2: str) -> bool:
    """Return True if v1 >= v2 (semver comparison)."""
    return _parse_version(v1) >= _parse_version(v2)


def _version_lt(v1: str, v2: str) -> bool:
    """Return True if v1 < v2 (semver comparison)."""
    return _parse_version(v1) < _parse_version(v2)


def _version_lte(v1: str, v2: str) -> bool:
    """Return True if v1 <= v2 (semver comparison)."""
    return _parse_version(v1) <= _parse_version(v2)


# Pattern that matches a version string: optional 'v' or 'ai_v' prefix,
# followed by at least one digit-dot-digit component (e.g. v1.2.3, 1.0.0).
_VERSION_STRING_RE = re.compile(
    r"^(?:ai_v|v)?[0-9]+(?:\.[0-9]+){1,2}$"
)


def _looks_like_version_string(value: str) -> bool:
    """Return True if value is a recognisable version string.

    Accepts forms such as 'v1.2.3', '1.2.3', 'ai_v1.2.3'.  Prose values
    such as '(internal — plugin era; no KI)' return False.

    This gate prevents changelog_writer from silently treating
    unrecognisable ## Affects content as version (0, 0, 0) and minting
    a Public ID for internal bugs.
    """
    return bool(_VERSION_STRING_RE.match(value.strip()))


def _warn_unparseable_affects(file_path: pathlib.Path, affects: str) -> None:
    """Emit a loud warning when ## Affects is non-empty but not a version string.

    The warning is written to stderr so it surfaces in CI logs and in any
    caller that captures stderr.  It names the bug file so the operator can
    locate and fix the value.
    """
    print(
        f"Warning: {file_path}: Affects value not a known release — "
        f"no Public ID assigned (## Affects: {affects!r})",
        file=sys.stderr,
    )


# ---------------------------------------------------------------------------
# Manifest loader
# ---------------------------------------------------------------------------


def load_published_manifest(repo_root: pathlib.Path) -> list[str]:
    """Load the list of publicly-released versions from release-notes/PUBLISHED.

    Returns a list of version strings (e.g. ['v1.0.0', 'v1.0.1']), oldest
    first (the order they appear in the file).

    Returns [] in two cases that share identical semantics — no published
    releases, every bug entry is internal:
      - The file exists but is empty (explicit pre-publication state).
      - The file is absent (implicit pre-publication state: managed dev trees
        that predate the v1.17 disclosure architecture have no PUBLISHED file,
        and an absent manifest is the semantically correct reading for
        local-only projects where nothing has ever been publicly released).

    Callers that want to distinguish "absent" from "empty" may check whether
    the file exists before calling this function; this function does not make
    that distinction because the downstream logic treats both identically.
    """
    manifest_path = pathlib.Path(repo_root) / "release-notes" / "PUBLISHED"
    if not manifest_path.exists():
        return []
    lines = manifest_path.read_text(encoding="utf-8").splitlines()
    return [line.strip() for line in lines if line.strip()]


# ---------------------------------------------------------------------------
# Bug file parser
# ---------------------------------------------------------------------------


def _parse_section_value(text: str, heading: str) -> str:
    """Extract the content under a ## <heading> section from markdown text.

    Returns the stripped content of the section body, or "" if the section
    is absent or empty. Stops at the next ## heading or end of file.
    """
    pattern = re.compile(
        r"^##\s+" + re.escape(heading) + r"\s*$",
        re.IGNORECASE | re.MULTILINE,
    )
    match = pattern.search(text)
    if not match:
        return ""
    start = match.end()
    # Find next ## heading
    next_heading = re.search(r"^##\s+", text[start:], re.MULTILINE)
    if next_heading:
        end = start + next_heading.start()
    else:
        end = len(text)
    return text[start:end].strip()


def _first_sentence(text: str) -> str:
    """Return the first sentence from a block of text.

    Newlines within the text are collapsed to spaces before scanning so that
    sentences that span multiple lines in the source file are returned as a
    single flat string.  This prevents multi-line symptom descriptions from
    producing rendered CHANGELOG lines with embedded newlines.
    """
    # Collapse all whitespace sequences (including newlines) to a single space
    text = " ".join(text.split())
    if not text:
        return ""
    # Split on period, exclamation, or question mark followed by space or end
    match = re.search(r"[.!?](?:\s|$)", text)
    if match:
        return text[: match.start() + 1].strip()
    # No sentence-ending punctuation — return the whole (now single-line) text
    return text


def _extract_bug_id(text: str) -> str:
    """Extract the canonical BUG-NNNN identifier from a bullet line.

    Matches BUG-NNNN (4 or more digits) only when the token is:
      - At the very start of the text (after optional whitespace / list markers)
      - Immediately after a '-' or '*' list marker and optional whitespace
      - Wrapped in markdown emphasis (``**BUG-NNNN**`` or ``*BUG-NNNN*``)

    Tokens embedded in free-text prose (e.g. "see BUG-92 for details") are
    deliberately NOT matched so that phantom IDs from inline comments do not
    produce spurious entries.
    """
    # Canonical token: exactly BUG-NNNN where NNNN is 4 or more digits
    canonical = r"BUG-(\d{4,})"

    # Pattern 1: leading position (after optional list marker / whitespace)
    #   e.g. "- BUG-0001 ..." or "* BUG-0001 ..." or "BUG-0001 ..."
    m = re.match(r"^[\s\-\*]*" + canonical, text.strip())
    if m:
        return f"BUG-{int(m.group(1)):04d}"

    # Pattern 2: emphasis — **BUG-NNNN** or *BUG-NNNN*
    m = re.search(r"\*{1,2}" + canonical + r"\*{1,2}", text)
    if m:
        return f"BUG-{int(m.group(1)):04d}"

    return ""


def parse_bug_file(path: pathlib.Path) -> BugRecord:
    """Parse a bug file and return a BugRecord.

    Fields absent from historical files are returned as empty strings.
    The bug_id is inferred from the filename (BUG-NNNN prefix).
    """
    text = path.read_text(encoding="utf-8")

    # Infer bug_id from filename
    filename = path.name  # e.g. "BUG-0023-tmux-split-flag.md"
    bug_id_match = re.match(r"(BUG-\d+)", filename, re.IGNORECASE)
    bug_id = bug_id_match.group(1).upper() if bug_id_match else filename
    # Normalize to BUG-NNNN (4-digit zero-padded)
    num_match = re.match(r"BUG-(\d+)", bug_id)
    if num_match:
        bug_id = f"BUG-{int(num_match.group(1)):04d}"

    slug = path.stem  # e.g. "BUG-0023-tmux-split-flag"

    status_raw = _parse_section_value(text, "Status").lower()
    status = status_raw.split()[0] if status_raw else "open"

    symptom_raw = _parse_section_value(text, "Symptom")
    # Strip HTML comments, then extract the first complete sentence.
    # A sentence ends at period / exclamation / question followed by whitespace
    # or end-of-string.  When no sentence boundary exists, fall back to the
    # first non-empty, non-comment line so that code-fence-only symptoms still
    # produce some (if ugly) output rather than an empty string.
    symptom_no_comments = re.sub(r"<!--.*?-->", "", symptom_raw, flags=re.DOTALL)
    symptom = _first_sentence(symptom_no_comments)
    if not symptom:
        # Fallback: first non-empty non-comment line
        for line in symptom_no_comments.splitlines():
            stripped = line.strip()
            if stripped:
                symptom = stripped
                break

    affects = _parse_section_value(text, "Affects").strip()
    # Strip inline comments from affects
    affects = re.sub(r"<!--.*?-->", "", affects, flags=re.DOTALL).strip()

    fixed_in = _parse_section_value(text, "Fixed In").strip()
    fixed_in = re.sub(r"<!--.*?-->", "", fixed_in, flags=re.DOTALL).strip()

    public_id = _parse_section_value(text, "Public ID").strip()
    public_id = re.sub(r"<!--.*?-->", "", public_id, flags=re.DOTALL).strip()

    # Extract wontdo reason from Status if applicable
    wontdo_reason = ""
    if "wontdo" in status_raw or "won't" in status_raw or "wont" in status_raw:
        # Look for a reason after the status keyword
        reason_match = re.search(
            r"won'?t\s*(?:do|fix)[:\s]+(.+)", status_raw, re.IGNORECASE
        )
        if reason_match:
            wontdo_reason = reason_match.group(1).strip()

    return BugRecord(
        bug_id=bug_id,
        slug=slug,
        symptom=symptom,
        status=status,
        affects=affects,
        fixed_in=fixed_in,
        public_id=public_id,
        wontdo_reason=wontdo_reason,
        file_path=path,
    )


def load_bugs(bugs_dir: pathlib.Path) -> list[BugRecord]:
    """Load all bug files from bugs_dir, sorted by bug_id ascending.

    Files that do not match the BUG-NNNN prefix are silently skipped.
    """
    if not bugs_dir.exists():
        return []
    records = []
    for path in sorted(bugs_dir.glob("BUG-*.md"), key=lambda p: p.name):
        try:
            records.append(parse_bug_file(path))
        except Exception as exc:  # noqa: BLE001
            # Log but do not abort — a corrupt bug file should not kill the build
            print(
                f"Warning: could not parse {path}: {exc}", file=sys.stderr
            )
    return records


# ---------------------------------------------------------------------------
# Release notes parser
# ---------------------------------------------------------------------------


def _parse_markdown_sections(text: str) -> dict[str, list[str]]:
    """Parse a markdown file into a dict of {heading_lower: [content_lines]}.

    Headings are matched at H2 (##) level; content is everything between
    consecutive H2 headings (or end of file). The H1 title line is skipped.
    """
    sections: dict[str, list[str]] = {}
    current_heading = None
    current_lines: list[str] = []

    for line in text.splitlines():
        # H1 title — skip
        if re.match(r"^#[^#]", line):
            continue
        # H2 heading
        h2_match = re.match(r"^##\s+(.+)$", line)
        if h2_match:
            if current_heading is not None:
                sections[current_heading] = current_lines
            current_heading = h2_match.group(1).strip().lower()
            current_lines = []
        elif current_heading is not None:
            current_lines.append(line)

    if current_heading is not None:
        sections[current_heading] = current_lines

    return sections


def _clean_content_lines(lines: list[str]) -> list[str]:
    """Strip leading/trailing blank lines from a content block.

    Also removes bare 'None' placeholder lines — these are used in release
    notes sections to indicate "nothing here", and should not be treated as
    actual content items by the writer.
    """
    # Remove leading blank lines
    while lines and not lines[0].strip():
        lines = lines[1:]
    # Remove trailing blank lines
    while lines and not lines[-1].strip():
        lines = lines[:-1]
    # Filter out bare 'None' placeholder values (case-insensitive)
    lines = [ln for ln in lines if ln.strip().lower() != "none"]
    return lines


def _join_bullet_continuations(lines: list[str]) -> list[str]:
    """Collapse multi-line markdown bullet items into single strings.

    A new bullet starts on any line that begins with ``-`` or ``*`` followed
    by whitespace.  Subsequent lines that do NOT start a new bullet are treated
    as continuation text and are joined (with a single space) to the current
    bullet.  Blank lines between bullets are discarded.

    Returns a list where each element is one complete (possibly multi-sentence)
    bullet text, suitable for passing to ``_extract_bug_id``.

    Non-bullet leading lines (e.g. a section opener that contains prose instead
    of a list) are returned as individual items unchanged.
    """
    bullets: list[str] = []
    current: list[str] = []

    _BULLET_RE = re.compile(r"^[\-\*]\s")

    def _flush() -> None:
        if current:
            bullets.append(" ".join(current))
            current.clear()

    for line in lines:
        if not line.strip():
            # Blank line — flush current bullet
            _flush()
            continue
        if _BULLET_RE.match(line):
            # New bullet
            _flush()
            current.append(line.strip())
        else:
            if current:
                # Continuation of the current bullet
                current.append(line.strip())
            else:
                # Plain line before any bullet (e.g. prose-only section body)
                bullets.append(line)

    _flush()
    return bullets


def parse_release_notes(version: str, notes_path: pathlib.Path) -> ReleaseEntry:
    """Parse a release-notes/vX.Y.Z.md file into a ReleaseEntry.

    Extracts:
    - date from the **Release Date:** field
    - summary from ## Summary (first sentence)
    - implemented_lines from ## Features / ## What Shipped / ## Implemented
    - fixed_bug_ids from ## Bug Fixes / ## Bugs Resolved (BUG-NNNN references)
    - fixed_other_lines from the same sections (non-BUG-NNNN items)
    """
    text = notes_path.read_text(encoding="utf-8")

    # Extract release date
    date_match = re.search(r"\*\*Release Date:\*\*\s*(\S+)", text)
    date = date_match.group(1) if date_match else ""

    sections = _parse_markdown_sections(text)

    # Summary
    summary = ""
    for heading in _SUMMARY_HEADINGS:
        if heading in sections:
            raw = "\n".join(sections[heading]).strip()
            summary = _first_sentence(raw)
            break

    # Implemented — collect from all implemented headings.
    # Sort headings alphabetically before iterating to guarantee a stable
    # collection order regardless of frozenset iteration (which is
    # PYTHONHASHSEED-dependent).  Without sorting, two runs with different
    # hash seeds can produce different line orderings when a release notes
    # file contains content under more than one matching heading.
    implemented_lines: list[str] = []
    for heading in sorted(_IMPLEMENTED_HEADINGS):
        if heading in sections:
            lines = _clean_content_lines(list(sections[heading]))
            if lines:
                implemented_lines.extend(lines)

    # Fixed — collect from all fixed headings, split into BUG ids and other.
    # Multi-line bullets (where continuation lines are indented or plain prose
    # following the opening "- " marker) are first joined into a single string
    # so that _extract_bug_id sees the full bullet and inline continuation lines
    # are not mistaken for separate items.
    # Sort headings alphabetically (same reason as for _IMPLEMENTED_HEADINGS
    # above — frozenset iteration order is hash-seed-dependent).
    fixed_bug_ids: list[str] = []
    fixed_other_lines: list[str] = []
    seen_bug_ids: set[str] = set()

    for heading in sorted(_FIXED_HEADINGS):
        if heading in sections:
            lines = _clean_content_lines(list(sections[heading]))
            bullets = _join_bullet_continuations(lines)
            for bullet in bullets:
                if not bullet.strip():
                    continue
                bug_id = _extract_bug_id(bullet)
                if bug_id:
                    if bug_id not in seen_bug_ids:
                        fixed_bug_ids.append(bug_id)
                        seen_bug_ids.add(bug_id)
                else:
                    fixed_other_lines.append(bullet)

    return ReleaseEntry(
        version=version,
        date=date,
        summary=summary,
        implemented_lines=implemented_lines,
        fixed_bug_ids=fixed_bug_ids,
        fixed_other_lines=fixed_other_lines,
    )


# ---------------------------------------------------------------------------
# Known Issues projection
# ---------------------------------------------------------------------------


def _earliest_published_gte(version: str, published: list[str]) -> str:
    """Return the earliest PUBLISHED version >= the given version, or ''."""
    candidates = [p for p in published if _version_gte(p, version)]
    if not candidates:
        return ""
    return min(candidates, key=_parse_version)


def _bug_intersects_published(
    bug: BugRecord, published: list[str]
) -> bool:
    """Return True if the bug's affected range intersects the PUBLISHED list.

    The bug must have a verified ## Affects field that parses as a version
    string (e.g. 'v1.0.0').  Prose values (e.g. '(internal — plugin era;
    no KI)') are not version strings; they never intersect any published range
    and return False without emitting a warning (the warning is emitted by
    the caller that drives Public-ID assignment).

    The affected range is [Affects, Fixed In) — open on the right for open
    bugs.  A bug "intersects published" if there exists any published version P
    such that P >= Affects AND (Fixed In is absent OR P < Fixed In).
    """
    if not bug.affects:
        return False  # Unverified affects — never disclose
    if not _looks_like_version_string(bug.affects):
        return False  # Prose or unrecognised value — never disclose
    for p in published:
        if _version_gte(p, bug.affects):
            if not bug.fixed_in or _version_lt(p, bug.fixed_in):
                return True
    return False


def _assign_public_id(
    bug: BugRecord,
    published: list[str],
    counters: dict[str, int],
) -> str:
    """Determine the Public ID for a disclosable bug.

    If the bug already has ## Public ID set in its file, return it as-is
    (IDs are immutable once assigned).

    Otherwise: find the earliest PUBLISHED version >= bug.affects, compute
    the next counter for that anchor, assign it, write it back to the bug
    file, and return the new ID.

    counters is a mutable dict {anchor_version_no_v: max_counter_seen} that
    the caller maintains across all bugs to track the next free counter.
    """
    if bug.public_id:
        # Already assigned — extract the anchor and update the counter
        # so future bugs in the same anchor get a higher number.
        id_match = re.match(r"KI-(\d+\.\d+\.\d+)\.(\d+)$", bug.public_id)
        if id_match:
            anchor = id_match.group(1)
            n = int(id_match.group(2))
            if counters.get(anchor, 0) < n:
                counters[anchor] = n
        return bug.public_id

    # Compute anchor: earliest PUBLISHED version >= bug.affects
    anchor_with_v = _earliest_published_gte(bug.affects, published)
    if not anchor_with_v:
        # No published version is >= affects — should not reach here
        # (caller already checked intersects_published)
        return ""

    anchor = anchor_with_v.lstrip("v")
    next_n = counters.get(anchor, 0) + 1
    counters[anchor] = next_n
    new_id = f"KI-{anchor}.{next_n}"

    # Persist the Public ID back to the bug file
    _write_public_id_to_bug_file(bug.file_path, new_id)

    return new_id


def _write_public_id_to_bug_file(file_path: pathlib.Path, public_id: str) -> None:
    """Append or update the ## Public ID field in a bug file.

    If ## Public ID section exists but is empty, fill it in.
    If it does not exist, append the section at the end.
    """
    text = file_path.read_text(encoding="utf-8")

    # Check if ## Public ID section exists (possibly with content)
    section_pattern = re.compile(
        r"(^##\s+Public ID\s*$)([\s\S]*?)(?=^##\s+|\Z)",
        re.MULTILINE,
    )
    match = section_pattern.search(text)
    if match:
        # Section exists — replace its content
        existing_content = match.group(2)
        # Extract just the non-comment part
        content_no_comment = re.sub(
            r"<!--[\s\S]*?-->", "", existing_content
        ).strip()
        if not content_no_comment:
            # Empty body — insert the value after the heading and any comments
            # Find the comment block in the existing content
            comment_match = re.search(r"<!--[\s\S]*?-->", existing_content)
            if comment_match:
                # Insert after the comment
                comment_end = match.start(2) + comment_match.end()
                new_text = (
                    text[: comment_end]
                    + f"\n{public_id}\n"
                    + text[comment_end:]
                )
            else:
                # No comment block — just append after heading
                heading_end = match.start(2)
                new_text = (
                    text[: heading_end]
                    + f"\n{public_id}\n"
                    + text[heading_end:].lstrip("\n")
                )
            file_path.write_text(new_text, encoding="utf-8")
        # else: already has content (should not happen if we only write once)
    else:
        # Section absent — append at end of file
        new_text = text.rstrip("\n") + f"\n\n## Public ID\n{public_id}\n"
        file_path.write_text(new_text, encoding="utf-8")


def remove_bogus_public_ids(
    bugs_dir: pathlib.Path,
    published_manifest: list[str],
) -> list[pathlib.Path]:
    """Remove Public IDs from bug files whose ## Affects does not parse as a version.

    This is the idempotent cleanup rider for hand-scrub recovery.  It scans
    every BUG-*.md file in bugs_dir and removes the ## Public ID value from
    any file where the ## Affects section is either absent, empty, or not a
    recognisable version string.

    A file is considered "clean" if it has no Public ID, or if its Affects
    value is a recognisable version string.  Clean files are not modified.

    The operation is idempotent: running it twice on the same directory
    produces the same result as running it once.

    Returns the list of file paths that were modified (Public ID removed).
    """
    bugs_dir = pathlib.Path(bugs_dir)
    modified: list[pathlib.Path] = []

    for path in sorted(bugs_dir.glob("BUG-*.md"), key=lambda p: p.name):
        try:
            rec = parse_bug_file(path)
        except Exception as exc:  # noqa: BLE001
            print(
                f"Warning: could not parse {path} during cleanup: {exc}",
                file=sys.stderr,
            )
            continue

        # No Public ID — nothing to remove.
        if not rec.public_id:
            continue

        # Affects is absent or parses as a valid version — keep the Public ID.
        if not rec.affects or _looks_like_version_string(rec.affects):
            continue

        # Affects is non-empty prose — this Public ID was bogusly minted.
        # Remove the Public ID value from the bug file.
        _remove_public_id_from_bug_file(path)
        modified.append(path)

    return modified


def _remove_public_id_from_bug_file(file_path: pathlib.Path) -> None:
    """Remove the content of the ## Public ID section in a bug file.

    Leaves the ## Public ID heading in place (with blank body) so the
    section structure is preserved.  Idempotent: calling on a file that
    already has a blank ## Public ID is a no-op (no bytes change).
    """
    text = file_path.read_text(encoding="utf-8")

    section_pattern = re.compile(
        r"(^##\s+Public ID\s*\n)([\s\S]*?)(?=^##\s+|\Z)",
        re.MULTILINE,
    )
    match = section_pattern.search(text)
    if not match:
        return  # No ## Public ID section — nothing to do.

    heading = match.group(1)
    body = match.group(2)

    # Strip the non-comment content from the body.
    # Preserve any HTML comment (e.g. the template instruction comment).
    # Strip only lines that carry an actual value.
    body_lines = body.splitlines(keepends=True)
    new_body_lines = []
    for line in body_lines:
        stripped = line.strip()
        # Keep blank lines and comment lines; drop value lines.
        if not stripped or stripped.startswith("<!--"):
            new_body_lines.append(line)
        else:
            # This is the value line — drop it.
            pass

    new_body = "".join(new_body_lines)
    if new_body == body:
        return  # Already clean — byte-identical, no write needed.

    new_text = text[: match.start()] + heading + new_body + text[match.end():]
    file_path.write_text(new_text, encoding="utf-8")


def _render_known_issue(
    bug: BugRecord,
    public_id: str,
    published: list[str],
) -> str:
    """Render a single Known Issue line in the CHANGELOG format.

    Format:
        KI-A.B.C.n — symptom; affects vA · fixed in vP
        KI-A.B.C.n — symptom; affects vA · fix pending next release
        KI-A.B.C.n — symptom; affects vA · open
        KI-A.B.C.n — symptom; affects vA · won't fix — reason
    """
    parts = [f"{public_id} — {bug.symptom}"]

    # Affects clause
    affects_str = f"affects {bug.affects}"

    # Fixed-in / status clause
    if "wontdo" in bug.status or "won't" in bug.status or "wont" in bug.status:
        reason = bug.wontdo_reason or "see bug ledger"
        fix_clause = f"won't fix — {reason}"
    elif bug.fixed_in:
        # Translate internal fixed_in to earliest published version >= it
        pub_fix = _earliest_published_gte(bug.fixed_in, published)
        if pub_fix:
            fix_clause = f"fixed in {pub_fix}"
        else:
            fix_clause = "fix pending next release"
    elif bug.status in ("resolved", "closed", "fixed"):
        # Resolved but Fixed In not yet written — treat as pending
        fix_clause = "fix pending next release"
    else:
        fix_clause = "open"

    parts.append(f"; {affects_str} · {fix_clause}")
    return "".join(parts)


def _build_known_issues_projection(
    bugs: list[BugRecord],
    published: list[str],
    entry_version: str,
) -> list[str]:
    """Build the Known Issues lines for a given CHANGELOG entry (version).

    A bug is rendered under the entry for the EARLIEST PUBLISHED version it
    affects. So this function returns lines only for bugs whose earliest
    affected PUBLISHED version is entry_version.

    The counters dict is managed externally (per regeneration call) so that
    Public IDs are assigned consistently across all entries.

    Returns a list of rendered lines (may be empty).
    """
    # This function is called after public IDs have already been assigned.
    # Filter bugs that anchor to this entry's version.
    lines = []
    for bug in bugs:
        if not bug.public_id:
            continue  # Not disclosed (no public ID assigned)
        # Find the anchor version for this bug
        anchor_with_v = _earliest_published_gte(bug.affects, published)
        if anchor_with_v != entry_version:
            continue
        line = _render_known_issue(bug, bug.public_id, published)
        lines.append(line)
    return lines


# ---------------------------------------------------------------------------
# Entry rendering
# ---------------------------------------------------------------------------


def _render_section(title: str, items: list[str], none_text: str = "None") -> str:
    """Render a ### section with a list of items, or a None placeholder."""
    if items:
        body = "\n".join(items)
        return f"### {title}\n{body}"
    else:
        return f"### {title}\n{none_text}"


def _strip_internal_ids(text: str) -> str:
    """Remove any BUG-NNNN references from text.

    Internal bug IDs must never appear in generated CHANGELOG output.
    This is applied as a final safety pass to each section.
    """
    # Replace "BUG-NNNN — " or "**BUG-NNNN**" etc. with just the remainder
    # Pattern: BUG-digits optionally followed by colon/dash/space markers
    cleaned = re.sub(
        r"\*{0,2}BUG-\d+\*{0,2}[:\s–—-]*",
        "",
        text,
    )
    return cleaned


def _render_fixed_items(
    entry: ReleaseEntry,
    bugs_by_id: dict[str, BugRecord],
    published: list[str],
) -> list[str]:
    """Render the Fixed section items for a release entry.

    - BUG-NNNN items:
        - Disclosed bug: render as "KI-A.B.C.n — symptom"
        - Internal-only bug: render as plain symptom line (no ID)
    - Non-BUG items: render as-is (stripped of any accidental BUG-NNNN refs)
    """
    lines = []

    for bug_id in entry.fixed_bug_ids:
        bug = bugs_by_id.get(bug_id)
        if bug is None:
            # Bug ID in release notes but no matching bug file.  This most
            # commonly happens when a phantom ID was extracted from inline prose
            # (e.g. "see BUG-92 for context").  Silently drop it so the
            # placeholder never surfaces in CHANGELOG output.
            continue
        if bug.public_id:
            # Disclosed bug — render with public ID and symptom
            lines.append(f"{bug.public_id} — {bug.symptom}")
        else:
            # Internal-only — render symptom with no identifier
            lines.append(bug.symptom if bug.symptom else "(internal fix)")

    for line in entry.fixed_other_lines:
        cleaned = _strip_internal_ids(line)
        if cleaned.strip():
            lines.append(cleaned.strip())

    return lines


# ---------------------------------------------------------------------------
# Main regeneration entry point
# ---------------------------------------------------------------------------


def regenerate(
    repo_root: pathlib.Path,
    released_versions: list[str],
    published_manifest: list[str],
    bugs_dir: pathlib.Path,
) -> str:
    """Regenerate the full CHANGELOG.md content as a string.

    Args:
        repo_root: Root of the git repository; release-notes/vX.Y.Z.md files
                   are read from here.
        released_versions: All release versions, newest first (e.g.
                           ['v1.16.3', 'v1.16.2', ..., 'v1.0.0']). Each must
                           have a corresponding release-notes/vX.Y.Z.md file.
        published_manifest: Versions publicly released, oldest first (e.g.
                            ['v1.0.0', 'v1.0.1']). May be empty (valid:
                            pre-publication state).
        bugs_dir: Path to the directory containing BUG-*.md files.

    Returns:
        The full text of the regenerated CHANGELOG.md.

    Notes:
        - When a disclosed bug lacks ## Public ID, this function assigns one
          and writes it back to the bug file (to ensure determinism on
          subsequent calls).
        - BUG-NNNN identifiers never appear in the returned string.
        - The returned string is deterministic: given unchanged inputs and bug
          files, two consecutive calls return byte-identical strings.
    """
    repo_root = pathlib.Path(repo_root)
    bugs_dir = pathlib.Path(bugs_dir)

    # --- Load and parse bugs ---
    all_bugs = load_bugs(bugs_dir)
    bugs_by_id: dict[str, BugRecord] = {b.bug_id: b for b in all_bugs}

    # --- Warn on non-empty Affects values that do not parse as a version ---
    # These bugs will never receive a Public ID.  The warning names the file
    # so the operator can correct or remove the malformed Affects value.
    # Internal bugs should omit the ## Affects section entirely.
    for b in all_bugs:
        if b.affects and not _looks_like_version_string(b.affects):
            _warn_unparseable_affects(b.file_path, b.affects)

    # --- Determine which bugs are disclosable ---
    # A bug is disclosable iff:
    #   1. It has a verified ## Affects field that parses as a version string
    #   2. Its affected range intersects the published manifest
    disclosable: list[BugRecord] = [
        b for b in all_bugs
        if _bug_intersects_published(b, published_manifest)
    ]

    # --- Assign Public IDs (modifies bug files on first assignment) ---
    # Sort disclosable bugs by (anchor_version, existing_id or file order)
    # to ensure consistent assignment order.
    # First pass: read existing IDs and build counter state.
    counters: dict[str, int] = defaultdict(int)
    for bug in disclosable:
        if bug.public_id:
            id_match = re.match(r"KI-(\d+\.\d+\.\d+)\.(\d+)$", bug.public_id)
            if id_match:
                anchor = id_match.group(1)
                n = int(id_match.group(2))
                if counters[anchor] < n:
                    counters[anchor] = n

    # Second pass: assign IDs to bugs that lack one, in a stable order
    # (sort by affects version ascending, then by bug_id ascending to break ties).
    needs_id = [b for b in disclosable if not b.public_id]
    needs_id.sort(key=lambda b: (_parse_version(b.affects), b.bug_id))

    # Rebuild disclosable with updated public_ids (we re-parse after writing).
    new_ids: dict[str, str] = {}
    for bug in needs_id:
        anchor_with_v = _earliest_published_gte(bug.affects, published_manifest)
        if not anchor_with_v:
            continue
        anchor = anchor_with_v.lstrip("v")
        counters[anchor] += 1
        new_id = f"KI-{anchor}.{counters[anchor]}"
        _write_public_id_to_bug_file(bug.file_path, new_id)
        new_ids[bug.bug_id] = new_id

    # Reload bugs to pick up newly written Public IDs
    if new_ids:
        all_bugs = load_bugs(bugs_dir)
        bugs_by_id = {b.bug_id: b for b in all_bugs}
        disclosable = [
            b for b in all_bugs
            if _bug_intersects_published(b, published_manifest)
        ]

    # --- Parse release notes ---
    notes_dir = repo_root / "release-notes"
    entries: list[ReleaseEntry] = []
    for version in released_versions:
        notes_path = notes_dir / f"{version}.md"
        if not notes_path.exists():
            # Skip versions with no notes file (should not happen in practice)
            continue
        entry = parse_release_notes(version, notes_path)
        entries.append(entry)

    # --- Build CHANGELOG content ---
    sections_text: list[str] = []

    for entry in entries:
        # Header line
        date_str = entry.date if entry.date else "unknown"
        entry_header = f"## {entry.version} — {date_str}"

        # Summary line (if present)
        summary_line = entry.summary if entry.summary else ""

        # Implemented section
        impl_lines = entry.implemented_lines
        impl_text = _render_section("Implemented", impl_lines, "None (bugfix release)")

        # Fixed section — classification is load-bearing:
        # a bundle with BUG items must never produce Fixed: None
        fixed_items = _render_fixed_items(entry, bugs_by_id, published_manifest)
        if not fixed_items and entry.fixed_bug_ids:
            # Should never happen: BUG items in release notes but no rendered output.
            # This indicates a bug file lookup failure — emit a placeholder.
            fixed_items = ["(one or more bug fixes — bug files unavailable)"]
        fixed_text = _render_section("Fixed", fixed_items)

        # Known Issues projection — render under earliest affected PUBLISHED version
        ki_lines_for_entry: list[str] = []
        if published_manifest:
            for bug in disclosable:
                if not bug.public_id:
                    continue
                anchor = _earliest_published_gte(bug.affects, published_manifest)
                if anchor == entry.version:
                    ki_line = _render_known_issue(bug, bug.public_id, published_manifest)
                    ki_lines_for_entry.append(ki_line)
        # Sort by public_id for determinism
        ki_lines_for_entry.sort()
        ki_text = _render_section("Known Issues", ki_lines_for_entry)

        # Detail link
        detail_link = (
            f"*Details: [release-notes/{entry.version}.md]"
            f"(release-notes/{entry.version}.md)*"
        )

        # Assemble entry
        entry_parts = [entry_header]
        if summary_line:
            entry_parts.append("")
            entry_parts.append(summary_line)
        entry_parts.append("")
        entry_parts.append(impl_text)
        entry_parts.append("")
        entry_parts.append(fixed_text)
        entry_parts.append("")
        entry_parts.append(ki_text)
        entry_parts.append("")
        entry_parts.append(detail_link)

        sections_text.append("\n".join(entry_parts))

    # Join all entries with separators
    body = "\n\n---\n\n".join(sections_text)
    if body:
        content = f"{_HEADER}\n---\n\n{body}\n\n---\n"
    else:
        content = f"{_HEADER}\n---\n"

    # Safety pass: verify no BUG-NNNN leaked through
    if _BUG_ID_PATTERN.search(content):
        # Strip any remaining references as a defensive measure,
        # then re-verify (this should not happen if the rendering logic
        # is correct, but we guard against future regressions).
        content = re.sub(
            r"\*{0,2}BUG-\d+\*{0,2}[:\s–—-]*",
            "",
            content,
        )

    return content


# ---------------------------------------------------------------------------
# CLI entry point (for testing from shell)
# ---------------------------------------------------------------------------


def _main() -> None:
    """Minimal CLI: regenerate CHANGELOG.md to stdout.

    Usage: python -m pgai_agent_kanban.cm.changelog_writer <repo_root> <bugs_dir> \\
               [version1 version2 ...]

    Versions are newest-first. If none are provided, they are discovered by
    scanning release-notes/vX.Y.Z.md files in the repo.
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="Regenerate CHANGELOG.md from release-notes and bug ledger."
    )
    parser.add_argument("repo_root", help="Root of the git repository.")
    parser.add_argument("bugs_dir", help="Directory containing BUG-*.md files.")
    parser.add_argument(
        "versions",
        nargs="*",
        help="Release versions newest-first. Auto-discovered if omitted.",
    )
    args = parser.parse_args()

    repo_root = pathlib.Path(args.repo_root)

    # Load published manifest (absent file = empty manifest: no published releases).
    published = load_published_manifest(repo_root)

    # Discover versions if not provided
    if args.versions:
        versions = args.versions
    else:
        notes_dir = repo_root / "release-notes"
        found = sorted(
            notes_dir.glob("v*.md"),
            key=lambda p: _parse_version(p.stem),
            reverse=True,
        )
        versions = [p.stem for p in found]

    bugs_dir = pathlib.Path(args.bugs_dir)
    content = regenerate(repo_root, versions, published, bugs_dir)
    sys.stdout.write(content)


if __name__ == "__main__":
    _main()
