"""
two_project.py
==============
Test-fidelity helper: build a kanban root containing two registered projects.

WHY THIS EXISTS (an earlier defect)
--------------------------
Before this helper, the test suite built only single-project fixtures.
Code paths that iterate over multiple projects (the wake-script outer loop,
the dashboard multi-project pane, the discovery pipeline's per-project
isolation) were either untested or tested with hand-rolled synthetic trees
that were inconsistent between test files.  A standard two-project fixture
closes the whole class of cross-project isolation bugs that single-project
fixtures cannot catch.

HOW TO USE
----------
As a plain function (any test file):

    from team.tests.fixtures.two_project import build_two_project_root

    root = build_two_project_root(tmp_path)
    # root is a pathlib.Path with:
    #   root/projects.cfg        — registers project_a (priority 1) and
    #                              project_b (priority 2)
    #   root/projects/project_a/ — full project tree
    #   root/projects/project_b/ — full project tree

As a pytest fixture (request in a test):

    def test_isolation(two_project_root):
        root = two_project_root
        # manipulate project_a without touching project_b

WHAT "FULL PROJECT TREE" MEANS
-------------------------------
Each project directory contains:
    release-state.md        — Active RC: none (idle state)
    project.cfg             — minimal INI config with project_name,
                              workflow_type=release, is_self_build=false
    tasks/queues/           — per-agent backlog files (coder, pm, writer,
                              tester, cm, bug, priority)
    tasks/queues/plans/     — PM materializer marker directory
    logs/                   — per-project log directory
    overwatch/backups/       — OVERWATCH state directories
    overwatch/actions.log    — empty OVERWATCH action log
    metrics/                — empty metrics directory

The kanban root also receives:
    kanban.cfg              — minimal INI config
    projects.cfg            — two-section INI registering project_a and project_b
    logs/                   — kanban-root log dir
    locks/                  — kanban-root lock dir
    workflows/              — plugin dirs: release/, document/ (with pipeline.yaml)
    tasks/queues/plans/     — root-level plans directory (legacy compat)

WHAT THIS HELPER DOES NOT DO
-----------------------------
- It does not run install.sh or create-project.sh.
- It does not create a dev tree or set env vars.  Callers that need env vars
  (PGAI_AGENT_KANBAN_ROOT_PATH, PGAI_TASKS_DIR) should set them via monkeypatch
  or the conftest autouse _block_live_kanban_writes fixture.
- Project names are fixed as "project_a" and "project_b" for determinism.
  Tests that need custom names should call the lower-level helpers directly.
"""

from __future__ import annotations

import pathlib
import shutil

import pytest

# ---------------------------------------------------------------------------
# Path constants
# ---------------------------------------------------------------------------

_TEAM_DIR = pathlib.Path(__file__).parent.parent.parent
_REAL_WORKFLOWS_DIR = _TEAM_DIR / "workflows"
# Workflow plugin directories to copy into test fixture roots.
# Each entry is a subdirectory under _REAL_WORKFLOWS_DIR containing at minimum
# workflow.cfg and workflow.sh; types with a pipeline.yaml (release, document)
# also carry it inside the directory so load_workflow() can resolve them.
_WORKFLOW_PLUGIN_DIRS = ["release", "document"]

# Fixed project names — deterministic, recognisable in logs.
PROJECT_A = "project_a"
PROJECT_B = "project_b"

# Per-agent backlog filenames (mirrors install.sh queue-initialisation block)
_QUEUE_FILES = [
    "coder_backlog.md",
    "pm_backlog.md",
    "writer_backlog.md",
    "tester_backlog.md",
    "cm_backlog.md",
    "bug_backlog.md",
    "priority_backlog.md",
]


# ---------------------------------------------------------------------------
# Low-level helper: build a single project directory
# ---------------------------------------------------------------------------


def _build_project_dir(projects_root: pathlib.Path, project_name: str) -> pathlib.Path:
    """Create one project directory under *projects_root/<project_name>/*.

    Called once per project by build_two_project_root().

    Args:
        projects_root:  The projects/ directory under the kanban root.
        project_name:   Name of the project to create.

    Returns:
        pathlib.Path — the newly created project directory.
    """
    proj = projects_root / project_name
    proj.mkdir(parents=True, exist_ok=True)

    # --- project.cfg (minimal INI) ---
    (proj / "project.cfg").write_text(
        f"# project.cfg — auto-generated by two_project fixture\n"
        f"# BUG-0160: two-project fixture for cross-project isolation testing.\n"
        f"\n"
        f"[project]\n"
        f"project_name = {project_name}\n"
        f"dev_tree_path = /dev/null\n"
        f"git_repo_url = git@example.com:{project_name}.git\n"
        f"git_remote_name = origin\n"
        f"workflow_type = release\n"
        f"is_self_build = false\n"
        f"\n"
        f"[versioning]\n"
        f"max_patch = 99\n"
        f"max_minor = 9\n"
        f"max_major = 0\n",
        encoding="utf-8",
    )

    # --- release-state.md (idle — no active RC) ---
    (proj / "release-state.md").write_text(
        "# Release State\n\n"
        "## Active RC\n"
        "none\n\n"
        "## RC Opened At\n"
        "none\n\n"
        "## RC Opened By Task\n"
        "none\n",
        encoding="utf-8",
    )

    # --- tasks/queues/ and per-agent backlog files ---
    queues_dir = proj / "tasks" / "queues"
    queues_dir.mkdir(parents=True, exist_ok=True)
    (queues_dir / "plans").mkdir(parents=True, exist_ok=True)

    for queue_file in _QUEUE_FILES:
        agent = queue_file.replace("_backlog.md", "")
        (queues_dir / queue_file).write_text(
            f"# {agent.upper()} Backlog\n\n"
            "<!-- Tasks are listed below. One task per line. -->\n"
            "<!-- Format: - [ ] TASK-ID -->\n",
            encoding="utf-8",
        )

    # --- per-project log directory ---
    (proj / "logs").mkdir(parents=True, exist_ok=True)

    # --- OVERWATCH state directories ---
    (proj / "overwatch" / "backups").mkdir(parents=True, exist_ok=True)
    (proj / "overwatch" / "actions.log").write_text("", encoding="utf-8")

    # --- metrics directory ---
    (proj / "metrics").mkdir(parents=True, exist_ok=True)

    return proj


# ---------------------------------------------------------------------------
# Core builder
# ---------------------------------------------------------------------------


def build_two_project_root(
    parent: pathlib.Path,
    subdir: str = "kanban_two_project",
) -> pathlib.Path:
    """Build a kanban root containing two registered projects.

    Creates a complete kanban root under *parent/<subdir>/* with two
    projects registered in projects.cfg (project_a at priority 1,
    project_b at priority 2).  Each project has the full directory
    structure expected by wake scripts, the discovery pipeline, and
    the dashboard.

    Args:
        parent:  Parent directory for the new root.  Caller is responsible
                 for choosing a temp path (e.g. pytest's tmp_path).
        subdir:  Name of the subdirectory to create under *parent*.
                 Defaults to "kanban_two_project".

    Returns:
        pathlib.Path — absolute path to the kanban root.

    Directory layout:
        <parent>/<subdir>/
            kanban.cfg
            projects.cfg        — registers project_a (p=1) and project_b (p=2)
            projects/
                project_a/      — full project tree (see _build_project_dir)
                project_b/      — full project tree (see _build_project_dir)
            logs/               — kanban-root logs
            logs/agents/        — per-firing wake-batch logs
            logs/debug/archive/ — debug log rotation target
            locks/              — flock files
            workflows/          — plugin dirs: release/, document/ (with pipeline.yaml)
            tasks/queues/plans/ — root-level plans dir (legacy compat)

    Design note: an earlier defect documented that the test suite built only
    single-project fixtures.  Tests using this fixture exercise multi-project
    isolation guarantees that single-project fixtures cannot reach.
    """
    root = parent / subdir
    root.mkdir(parents=True, exist_ok=True)

    # --- kanban.cfg ---
    (root / "kanban.cfg").write_text(
        "# kanban.cfg — minimal two-project fixture config\n"
        "# BUG-0160: two-project fixture for cross-project isolation testing.\n"
        "\n"
        "[paths]\n"
        "\n"
        "[chain]\n"
        "pm_mode = automatic\n"
        "\n"
        "[wake]\n"
        "max_tasks_per_wake = 1\n"
        "max_runtime_seconds = 600\n",
        encoding="utf-8",
    )

    # --- projects.cfg: register both projects ---
    (root / "projects.cfg").write_text(
        "# projects.cfg — two-project fixture registry\n"
        "# BUG-0160: two-project fixture for cross-project isolation testing.\n"
        "\n"
        f"[project:{PROJECT_A}]\n"
        "priority=1\n"
        f"description=First fixture project (A)\n"
        "enabled=true\n"
        "\n"
        f"[project:{PROJECT_B}]\n"
        "priority=2\n"
        f"description=Second fixture project (B)\n"
        "enabled=true\n",
        encoding="utf-8",
    )

    # --- kanban-root runtime directories ---
    (root / "logs" / "agents").mkdir(parents=True, exist_ok=True)
    (root / "logs" / "debug" / "archive").mkdir(parents=True, exist_ok=True)
    (root / "locks").mkdir(parents=True, exist_ok=True)

    # --- Legacy root-level plans directory ---
    (root / "tasks" / "queues" / "plans").mkdir(parents=True, exist_ok=True)

    # --- workflows/: plugin directories (mirror install.sh behaviour) ---
    # install.sh copies team/workflows/ (including plugin subdirs) to
    # $KANBAN_ROOT/workflows/.  Each plugin dir contains workflow.cfg,
    # workflow.sh, and optionally pipeline.yaml (release and document carry one).
    wf_dir = root / "workflows"
    wf_dir.mkdir(parents=True, exist_ok=True)
    for plugin_name in _WORKFLOW_PLUGIN_DIRS:
        src_plugin = _REAL_WORKFLOWS_DIR / plugin_name
        if src_plugin.is_dir():
            dest_plugin = wf_dir / plugin_name
            if dest_plugin.exists():
                shutil.rmtree(dest_plugin)
            shutil.copytree(src_plugin, dest_plugin)

    # --- Build each project directory ---
    projects_root = root / "projects"
    projects_root.mkdir(parents=True, exist_ok=True)
    _build_project_dir(projects_root, PROJECT_A)
    _build_project_dir(projects_root, PROJECT_B)

    return root


# ---------------------------------------------------------------------------
# pytest fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def two_project_root(tmp_path: pathlib.Path) -> pathlib.Path:
    """Pytest fixture: return a kanban root containing two registered projects.

    The root contains project_a (priority 1) and project_b (priority 2),
    each with a full project tree.  The two projects are isolated from each
    other — modifying project_a's release state does not affect project_b's.

    Composes with conftest.py's _block_live_kanban_writes autouse fixture.
    Callers that need env vars (PGAI_AGENT_KANBAN_ROOT_PATH, etc.) to point
    at this root should use monkeypatch:

        def test_discovery_isolation(two_project_root, monkeypatch):
            monkeypatch.setenv("PGAI_AGENT_KANBAN_ROOT_PATH", str(two_project_root))
            # ... exercise multi-project discovery path ...

    an earlier defect: this fixture closes the test-fidelity gap where single-project
    fixtures could not exercise cross-project isolation guarantees.
    """
    return build_two_project_root(tmp_path)
